version: '3.7'

services:

  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    restart: always
    volumes:
    - /Users/zhaojm/tmp/data:/data

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    restart: always
    volumes:
    - /Users/zhaojm/tmp/data:/data

  consul:
    image: consul:latest
    restart: always
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  micro-api:
    command: --register_ttl=30 --register_interval=15 --client_retries=5 api --handler=api
    #      --cors-allowed-headers=* \
    #      --cors-allowed-origins=* \
    #      --cors-allowed-methods=POST
    #    image: microhq/micro:latest
    #    image: micro-cors
    #    build: ./micro-cors
    image: mingz2013/micro-cors
    restart: always
    links:
    - consul
    #    - todos-api
    ports:
    - "8080:8080"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"

      CORS_ALLOWED_HEADERS: "*"
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "POST"

  micro-web:
    command: --register_ttl=30 --register_interval=15 --client_retries=5 web
    #      --cors-allowed-headers=* \
    #      --cors-allowed-origins=* \
    #      --cors-allowed-methods=POST
    #    image: microhq/micro:latest
    #    image: micro-cors
    #    build: ./micro-cors
    image: mingz2013/micro-cors
    restart: always
    links:
    - consul
    #    - todos-web
    ports:
    - "8082:8082"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"

      CORS_ALLOWED_HEADERS: "*"
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "POST"


  todos-api:
    #    build: ./api/todos
    image: mingz2013/todos-api
    command: --register_ttl=30 --register_interval=15 --client_retries=5
    #    command: --cors-allowed-headers=Content-Type \
    #      --cors-allowed-origins=* \
    #      --cors-allowed-methods=POST
    #    ports:
    #    - 50051:50051
    links:
    - consul
    #    - todos-srv
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
  #      MICRO_ADDRESS: ":50051"
  #      CORS_ALLOWED_HEADERS: "X-Custom-Header, Content-Type"
  #      CORS_ALLOWED_ORIGINS: "*"
  #      CORS_ALLOWED_METHODS: "POST"

  todos-web:
    #    build: ./web/todos
    image: mingz2013/todos-web
    command: --register_ttl=30 --register_interval=15 --client_retries=5
    #      --cors-allowed-headers=Content-Type \
    #      --cors-allowed-origins=* \
    #      --cors-allowed-methods=POST
    #    ports:
    #    - 50052:50052
    links:
    - consul
    #    - todos-srv
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
  #      MICRO_ADDRESS: ":50052"
  #      CORS_ALLOWED_HEADERS: "X-Custom-Header, Content-Type"
  #      CORS_ALLOWED_ORIGINS: "*"
  #      CORS_ALLOWED_METHODS: "POST"


  todos-srv:
    #    build: ./srv/todos
    image: mingz2013/todos-srv
    #    ports:
    #    - 50053:50053
    command: --register_ttl=30 --register_interval=15 --client_retries=5
    links:
    - redis
    - mongo
    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"

      DB_HOST: "mongo:27017"

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

#      MICRO_ADDRESS: ":50053"




