version: '3.3'

services:

  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    restart: always
    volumes:
    - /Users/zhaojm/tmp/data:/data

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    restart: always
    volumes:
    - /Users/zhaojm/tmp/data:/data

  consul:
    command: -server -bootstrap -rejoin
    image: progrium/consul:latest
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  micro-api:
    command: --registry_address=consul:8500 api --handler=rpc
    image: microhq/micro:latest
    links:
    - consul
    - todos-api
    ports:
    - "8080:8080"

  micro-web:
    command: --registry_address=consul:8500 web
    image: microhq/micro:latest
    links:
    - consul
    - todos-web
    ports:
    - "8082:8082"


  todos-api:
    build: ./api/todos
    command: --registry_address=consul:8500
    ports:
    - 50051:50051
    links:
    - consul
    - todos-srv
    environment:
      MICRO_ADDRESS: ":50051"

  todos-web:
    build: ./web/todos
    command: --registry_address=consul:8500
    ports:
    - 50052:50052
    links:
    - consul
    - todos-srv
    environment:
      MICRO_ADDRESS: ":50052"


  todos-srv:
    build: ./srv/todos
    command: --registry_address=consul:8500
    ports:
    - 50053:50053
    links:
    - redis
    - mongo
    - consul
    environment:
      MICRO_ADDRESS: ":50053"
      DB_HOST: "mongo:27017"



