version: '3.3'

services:

  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    restart: always
    volumes:
    - /Users/zhaojm/tmp/data:/data

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    restart: always
    volumes:
    - /Users/zhaojm/tmp/data:/data

  consul:
    image: consul:latest
    restart: always
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  micro-api:
    command: api --handler=api
    image: microhq/micro:latest
    restart: always
    #    links:
    #    - consul
    #    - todos-api
    ports:
    - "8080:8080"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"

  micro-web:
    command: web
    image: microhq/micro:latest
    restart: always
    #    links:
    #    - consul
    #    - todos-web
    ports:
    - "8082:8082"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"


  todos-api:
    build: ./api/todos
    #    ports:
    #    - 50051:50051
    #    links:
    #    - consul
    #    - todos-srv
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
  #      MICRO_ADDRESS: ":50051"

  todos-web:
    build: ./web/todos
    #    ports:
    #    - 50052:50052
    #    links:
    #    - consul
    #    - todos-srv
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
  #      MICRO_ADDRESS: ":50052"


  todos-srv:
    build: ./srv/todos
    #    ports:
    #    - 50053:50053
    #    links:
    #    - redis
    #    - mongo
    #    - consul
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul:8500"

      DB_HOST: "mongo:27017"

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

#      MICRO_ADDRESS: ":50053"




