// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/todo/todo.proto

package go_micro_srv_todos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TodoInterface service

type TodoInterfaceService interface {
	Add(ctx context.Context, in *AddReq, opts ...client.CallOption) (*AddResp, error)
	Del(ctx context.Context, in *DelReq, opts ...client.CallOption) (*DelResp, error)
	Edit(ctx context.Context, in *EditReq, opts ...client.CallOption) (*EditResp, error)
	List(ctx context.Context, in *ListReq, opts ...client.CallOption) (*ListResp, error)
	Detail(ctx context.Context, in *DetailReq, opts ...client.CallOption) (*DetailResp, error)
}

type todoInterfaceService struct {
	c    client.Client
	name string
}

func NewTodoInterfaceService(name string, c client.Client) TodoInterfaceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.todos"
	}
	return &todoInterfaceService{
		c:    c,
		name: name,
	}
}

func (c *todoInterfaceService) Add(ctx context.Context, in *AddReq, opts ...client.CallOption) (*AddResp, error) {
	req := c.c.NewRequest(c.name, "TodoInterface.Add", in)
	out := new(AddResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoInterfaceService) Del(ctx context.Context, in *DelReq, opts ...client.CallOption) (*DelResp, error) {
	req := c.c.NewRequest(c.name, "TodoInterface.Del", in)
	out := new(DelResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoInterfaceService) Edit(ctx context.Context, in *EditReq, opts ...client.CallOption) (*EditResp, error) {
	req := c.c.NewRequest(c.name, "TodoInterface.Edit", in)
	out := new(EditResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoInterfaceService) List(ctx context.Context, in *ListReq, opts ...client.CallOption) (*ListResp, error) {
	req := c.c.NewRequest(c.name, "TodoInterface.List", in)
	out := new(ListResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoInterfaceService) Detail(ctx context.Context, in *DetailReq, opts ...client.CallOption) (*DetailResp, error) {
	req := c.c.NewRequest(c.name, "TodoInterface.Detail", in)
	out := new(DetailResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoInterface service

type TodoInterfaceHandler interface {
	Add(context.Context, *AddReq, *AddResp) error
	Del(context.Context, *DelReq, *DelResp) error
	Edit(context.Context, *EditReq, *EditResp) error
	List(context.Context, *ListReq, *ListResp) error
	Detail(context.Context, *DetailReq, *DetailResp) error
}

func RegisterTodoInterfaceHandler(s server.Server, hdlr TodoInterfaceHandler, opts ...server.HandlerOption) error {
	type todoInterface interface {
		Add(ctx context.Context, in *AddReq, out *AddResp) error
		Del(ctx context.Context, in *DelReq, out *DelResp) error
		Edit(ctx context.Context, in *EditReq, out *EditResp) error
		List(ctx context.Context, in *ListReq, out *ListResp) error
		Detail(ctx context.Context, in *DetailReq, out *DetailResp) error
	}
	type TodoInterface struct {
		todoInterface
	}
	h := &todoInterfaceHandler{hdlr}
	return s.Handle(s.NewHandler(&TodoInterface{h}, opts...))
}

type todoInterfaceHandler struct {
	TodoInterfaceHandler
}

func (h *todoInterfaceHandler) Add(ctx context.Context, in *AddReq, out *AddResp) error {
	return h.TodoInterfaceHandler.Add(ctx, in, out)
}

func (h *todoInterfaceHandler) Del(ctx context.Context, in *DelReq, out *DelResp) error {
	return h.TodoInterfaceHandler.Del(ctx, in, out)
}

func (h *todoInterfaceHandler) Edit(ctx context.Context, in *EditReq, out *EditResp) error {
	return h.TodoInterfaceHandler.Edit(ctx, in, out)
}

func (h *todoInterfaceHandler) List(ctx context.Context, in *ListReq, out *ListResp) error {
	return h.TodoInterfaceHandler.List(ctx, in, out)
}

func (h *todoInterfaceHandler) Detail(ctx context.Context, in *DetailReq, out *DetailResp) error {
	return h.TodoInterfaceHandler.Detail(ctx, in, out)
}
